---
name: tests

on:
  push:
    branches-ignore:
    - 'development/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - name: install dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: lint
      run: yarn --silent lint

    - name: build
      run: yarn --silent build

    - name: test and coverage
      run: yarn --silent coverage

    - uses: codecov/codecov-action@v2
